project2/bids/urls.py
from django.urls import path
from . import views

app_name = 'bids'

urlpatterns = [
    path('', views.FilmListView.as_view(), name='all'),
    #path('open', views.openpage, name='openpage'),
    path('bids/<int:pk>/detail', views.FilmDetailView.as_view(), name='bid_detail'),
    path('bids/create/', views.FilmCreateView.as_view(), name='bid_create'),
    path('bids/<int:pk>/update/', views.FilmUpdateView.as_view(), name='bid_update'),
    path('bids/<int:pk>/delete/', views.FilmDeleteView.as_view(), name='bid_delete'),
    path('bids/<int:pk>/delete/', views.FilmDeleteView.as_view(), name='bid_delete'),
    path("index1", views.index1, name="index1")

]

project2/project/urls.py
from django.contrib import admin
from django.urls import path, include # added
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('bids.urls')), # added
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) #added

project2/bids/models.py
from django.db import models

from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator



class Bid(models.Model):
    bid_description  = models.CharField(blank = True, max_length =255 )
    End_user = models.CharField(blank = True, max_length =255 )
    activity_type = models.CharField(blank = True, max_length =255 )
    reference_no = models.CharField(blank = True, max_length =50,primary_key=True )
    last_date_of_clarifications = models.CharField(blank = True, max_length =50 )
    bid_information = models.ImageField(upload_to='static',blank = True)
    bid_documnts = models.FileField(upload_to='media',blank = True)



project2/bids/views.py
from django.shortcuts import render

from django.views import View
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Bid

class FilmBaseView(View):
    model = Bid
    fields = '__all__'
    success_url = reverse_lazy('bids:all')

class FilmListView(FilmBaseView, ListView):
    """View to list all bids.
    Use the 'film_list' variable in the template
    to access all Film objects"""

class FilmDetailView(FilmBaseView, DetailView):
    """View to list the details from one film.
    Use the 'film' variable in the template to access
    the specific film here and in the Views below"""

class FilmCreateView(FilmBaseView, CreateView):
    """View to create a new film"""

class FilmUpdateView(FilmBaseView, UpdateView):
    """View to update a film"""

class FilmDeleteView(FilmBaseView, DeleteView):
    """View to delete a film"""
from django.http import FileResponse

def index1(request):
    if request.method=='POST':
        upload1 = request.FILES['Bid']
        object = Bid.objects.create(upload=upload1)
        object.save()
    context = Bid.objects.all()
    return render(request,'bid_list.html',{'context':context})

project2/bids/templates/base.html
<!DOCTYPE HTML>
<html lang="en">

<head>

<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">


{% block title %}
    {% if title %}
        <title> My Bids</title>
    {% else %}
        <title>My Bids</title>
    {% endif %}
{% endblock title %}

{% block head %}
{% endblock head %}

</head>

<body>

<div class="container-fluid">

    <!-- NAVIGATION BAR -->


    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="d-flex justify-content-between px-5 mx-auto" style="width: 80%;">
            <span class="navbar-text text-white">My Bids</span>
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link active" href="{% url 'bids:all' %}"></a>
                </li>

                <!--
                ##
                ## UNCOMMENT THESE LINES IF YOU HAVE A FUNCTIONAL CRUD FOR THE GENRE MODEL
                ## CHANGE ALSO THE URL INFO 'bids:all' to 'bids:genre_all'

                <li class="nav-item active">
                    <a class="nav-link active" href="{% url 'bids:all' %}">Genres</a>
                </li>

                -->

                <li class="nav-item active">
                    <a class="nav-link active" href="https://linktr.ee/fabriciobarbacena" target="_blank"></a>
                </li>
            </ul>
        </div>
    </nav>

    <!-- END OF NAVIGATION BAR -->

</div>

{% block content %}
{% endblock content %}


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>

</body>

</html>

project2/bids/templates/bids/bid_confirm_delete.html
{% extends "base.html" %}

{% block content %}

{% url 'films:all' as list_all %}

<div class="container d-flex justify-content-center mt-5" style="width: 50%;">
    <div class="col mt-5 text-center">
        <h1 class="mb-5">Delete Film</h1>

        <p class="h5">Are you sure you want to delete the Film:</p>
        <h3 class="my-5">{{ film.title }}</h3>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% comment %} <input type="submit" value="Confirm">
            <input type="submit" value="Cancel" onclick="window.location='{% url 'films:all' %}'; return false;"> {% endcomment %}
            <input type="submit" class="btn btn-primary btn-lg" value="Confirm" style="margin-right: 30px; margin-top: 30px;">
            <input type="submit" class="btn btn-danger btn-lg" style="margin-top: 30px;" onclick="window.location='{{list_all}}'; return false;" value="Cancel">
        </form>
    </div>
</div>

{% endblock %}

project2/bids/templates/bids/bid_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-5" style="width: 70%;">
    <div class="col">
        <h1 class="text-center">Film Details</h1>
        <div class="d-flex justify-content-center">
            <table class="table table-striped mt-5" style="width: 50%">
                <thead>
                    <tr>
                        <th scope="col"></th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                
                    {% for label, value in film.get_fields  %}
                        <tr>
                            <td>{{label | upper}}</td>
                            <td>{{value}}</td>
                        </tr>
                    {% endfor %}
                        
                </tbody>
            </table>
        </div>

        <div class="d-flex justify-content-center">
            <a href="{% url 'films:all' %}" class="d-block btn btn-primary btn-lg my-5">BACK</a>
        </div>
    </div>
        
</div>

{% endblock  %}

project2/bids/templates/bids/bid_form.html
{% extends "base.html" %}

{% block content %}

<!-- BOOTSTRAP FORM -->

<div class="container d-flex justify-content-center mt-5" style="width: 25%;">
    <div class="col mt-5">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <table class="table">
                {{form.as_table}}
            </table>
            <div class="container d-flex justify-content-center" style="width: 10%;">
                <input type="submit" class="btn btn-primary btn-lg" value="Submit" style="margin-right: 30px; margin-top: 30px;">
                <input type="submit" class="btn btn-danger btn-lg" style="margin-top: 30px;" onclick="window.location='{% url 'bids:all' %}'; return false;" value="Cancel">
            </div>    
        </form> 

    </div>
</div>

<!-- END BOOTSTRAP FORM -->

{% endblock %}

project2/bids/templates/bids/bid_list.html
{% extends 'base.html' %}

{% block content %}
{% for film in film_list %}
    {% for colname in film.column_set.all  %}
        <p>{{colname}}</p>
    {% endfor %}
{% endfor %}


<div class="container d-flex mt-10" style="width: 150%;">
    <div class="col">
        <h1 class="text-center"> BIDS</h1>
        <table class="table table-striped mt-5">
            <thead>
                <tr>
                    {% comment %} <th>#</th> {% endcomment %}
                    {% comment %} <th>#</th> {% endcomment %}
                    <th class="text-center" scope="col">Reference No.</th>
                    <th class="text-center" scope="col">Bid Info.</th>
                    <th class="text-center" scope="col">Bid Docu.</th>
                    <th class="text-center" scope="col">Update</th>
                    <th class="text-center" scope="col">Delete</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            
                {% for bid in bid_list %}
                <tr>
                    {% comment %} <th scope="row">{{forloop.counter}}</th> {% endcomment %}
                    <td class="text-center">{{bid.reference_no}}</td>
                    <td>{% if bid.bid_information %}<img src="/media/{{ bid.bid_information }}" class="img img-responsive" width="900px">{% endif %}</td>
                    <td class="text-center" scope="col" ><a href="{{ bids.bid_documnts.url}}"download="{{ bids.bid_documnts.url}}">Download</a></td>

                    <td><a href="{% url 'bids:bid_update' bid.reference_no %} ">Update</a></td>
                    <td><a href="{% url 'bids:bid_delete' bid.reference_no %}">Delete</a></td>
                </tr>
            {% endfor %}
        
            </tbody>
        </table>    
        <div class="d-flex justify-content-center">
            <a href="{% url 'bids:bid_create' %}" class="d-block btn btn-primary btn-lg my-5">Add New</a>
        </div>
    </div>
        
</div>

{% endblock content %}